import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Link from 'next/link';
import styles from "./rootStyle.module.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <header className={styles.header}>
        <h1 className={styles.homeLink}>
        <Link href="/home">Globomantics</Link>
        </h1>
      <h2 className={styles.menuBarLink}>
          <Link href="/blog">Blog</Link>
        </h2>
        <h2 className={styles.menuBarLink}>
          <Link href="/settings">Settings</Link>
        </h2>
        <h2 className={styles.menuBarLink}>
          <Link href="/conference">Conference</Link>
        </h2>
        </header>

        {children}
      </body>
    </html>
  );
}
